import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import BooksContext from "./context/BooksContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const response = await fetch(
  "https://aspinchakma.github.io/api-for-practice/booksData.json",
);

const books = await response.json();

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <BooksContext booksData={books}>
          <Navbar />
          <main className="flex-1 lg:w-7xl mx-auto border-2">{children}</main>
          <Footer />
        </BooksContext>
      </body>
    </html>
  );
}
